# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VehicleConnectSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VehicleConnectSDK

    pod 'AppAuth', '1.7.6'
    pod 'SwiftLint'

  target 'VehicleConnectSDKTests' do
    # Pods for testing
  end

end
