name: Generate Swift Documentation

on:
  workflow_dispatch:  # allows manual trigger
  push:
    branches: [main]  # or any branch you want

jobs:
  generate-docs:
    name: Build DocC Documentation
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'  # Use a version supporting DocC

      - name: Install CocoaPods
        run: brew install cocoapods

      - name: Install Dependencies
        run: |
          cd VehicleConnectSDK
          pod install

      - name: Build Documentation
        run: |
          cd VehicleConnectSDK
          xcodebuild docbuild \
            -scheme VehicleConnectSDK \
            -destination 'generic/platform=iOS' \
            -derivedDataPath ./DerivedData \
            -workspace VehicleConnectSDK.xcworkspace

          # Export to a static HTML doc
          DOCC_OUTPUT_PATH="./VehicleConnectDocs"
          DOCC_ARCHIVE_PATH="./DerivedData/Build/Products/Debug-iphoneos/VehicleConnectSDK.doccarchive"

          xcrun docc process-archive transform-for-static-hosting "$DOCC_ARCHIVE_PATH" \
            --output-path "$DOCC_OUTPUT_PATH" \
            --hosting-base-path VehicleConnectDocs

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VehicleConnectSDK-Docs
          path: VehicleConnectSDK/VehicleConnectDocs
