name: Documentation

on:
   push:
    branches: [ "*" ]
   pull_request:
    branches: [ "*" ]
   workflow_dispatch:
jobs:
  documentation:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Checkout external template repository
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          repository: HARMAN-Automotive/CSP-Documentation
          path: CSP-Documentation
          token: ${{ secrets.REPO_TOKEN }}

      - name: Check files in the working directory
        run: |
          pwd
          ls

      - name: Configure Git
        id: git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install cyclonedx-cocoapods
        shell: bash
        run: gem install cyclonedx-cocoapods -v ${{ '1.2.0' }}
      - name: Dependencies install
        run: |
         cd VehicleConnectSDK
         pod install 
      - name: Run cyclonedx-cocoapods
        shell: bash
        run: cyclonedx-cocoapods -p ${{ github.workspace }}/VehicleConnectSDK -v 1.0 -t framework --output ${{ github.workspace }}/VehicleConnectSDK/bom.xml
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Archive SBOM
        run: cp ${{ github.workspace }}/VehicleConnectSDK/bom.xml ./bom.xml

      - name: Download templates
        run: |
          cp ./CSP-Documentation/scripts/notice-generator.py ./notice-generator.py
          cp ./CSP-Documentation/template/NOTICE.template.md ./NOTICE.template
          cp ./CSP-Documentation/template/CODE_OF_CONDUCT.template.md ./CODE_OF_CONDUCT.md
          cp ./CSP-Documentation/template/SECURITY.template.md ./SECURITY.md
          cp ./CSP-Documentation/template/CONTRIBUTING.template.md ./CONTRIBUTING.md
          sed -i.bu "s|{{repository}}|${{ github.repository }}|g" ./NOTICE.template
          sed -i.bu "s|{{repository}}|${{ github.repository }}|g" ./CONTRIBUTING.md
      - name: Allow notice script to be executed
        run: chmod +x ./notice-generator.py

      - name: Execute script
        run: python ./notice-generator.py

      - name: Commit NOTICE
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git add NOTICE.md CODE_OF_CONDUCT.md CONTRIBUTING.md SECURITY.md
          git diff-index --quiet HEAD || git commit -am "Generate Documentation"
          git push
