name: Build Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build iOS Framework
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.3'

    - name: Install CocoaPods
      run: brew install --formula cocoapods

    - name: Install Dependencies
      run: |
        cd VehicleConnectSDK
        pod repo update
        pod install

    - name: Build Framework
      run: |
        cd VehicleConnectSDK

        xcodebuild clean archive \
          -scheme VehicleConnectSDK \
          -destination 'generic/platform=iOS' \
          -archivePath $PWD/build/ios_devices.xcarchive \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

        xcodebuild clean archive \
          -scheme VehicleConnectSDK \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath $PWD/build/ios_simulator.xcarchive \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

        xcodebuild -create-xcframework \
          -framework build/ios_devices.xcarchive/Products/Library/Frameworks/VehicleConnectSDK.framework \
          -framework build/ios_simulator.xcarchive/Products/Library/Frameworks/VehicleConnectSDK.framework \
          -output VehicleConnectSDK.xcframework

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VehicleConnectSDK.xcframework
        path: VehicleConnectSDK/VehicleConnectSDK.xcframework
