name: Build Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build iOS Framework
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Install Dependencies
      run: |
        brew install cocoapods || true
        pod install

    - name: Build Framework
      run: |
        xcodebuild clean archive \
          -scheme VehicleConnectSDK \
          -destination 'generic/platform=iOS' \
          -archivePath $PWD/build/ios_devices.xcarchive \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

        xcodebuild clean archive \
          -scheme VehicleConnectSDK \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath $PWD/build/ios_simulator.xcarchive \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

        xcodebuild -create-xcframework \
          -framework build/ios_devices.xcarchive/Products/Library/Frameworks/VehicleConnectSDK.framework \
          -framework build/ios_simulator.xcarchive/Products/Library/Frameworks/VehicleConnectSDK.framework \
          -output VehicleConnectSDK.xcframework

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VehicleConnectSDK.xcframework
        path: VehicleConnectSDK.xcframework
