name: License Compliance

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write

jobs:
  check-licenses:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies install
        run: |
         cd VehicleConnectSDK
         pod install
      - name: Allow dash.sh to be executed
        run: chmod +x ./eclipse-dash/dash.sh
      - name: Generate List of dependencies
        run: ./eclipse-dash/dash.sh
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          scheme: ${{ 'default' }}
      - name: Archive Third Party DEPENDENCIES file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: LICENSE_INFO_THIRD_PARTY_DEPENDENCIES
          path: DEPENDENCIES
